#Cloudbuild.yaml
steps:
#I want to build the container Image
# name: u need to mention the builder name
- name: 'gcr.io/cloud-builders/docker'
  # docker build -t gcr.io/projectID/reposname:tagName
  args: ['build', '-t', 'gcr.io/${_PROJECT}/build-run-image:v1', 'build-run/.']
  # push the image to google container registroy 
- name: 'gcr.io/cloud-builders/docker'
  # docker push gcr.io/$PROJECT_ID/reposname:tageName
  args: ['push', 'gcr.io/${_PROJECT}/build-run-image:v1']
  # gcloud builds submit --tag gcr.io/$PROJECT_ID/build-run-image
  # Deploy container Image to cloud run 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'cloud-run-deploy', '--image', 'gcr.io/$PROJECT_ID/build-run-image:v1', '--region', '${_REGION}', '--allow-unauthenticated']
  #gcloud run deploy image cloud-run-deploy --image=gcr.io/$PROJECT_ID/build-run-image --region=us-central1 --allow-unauthenticated
substitutions:
  _PROJECT: test-405413
  _REGION: us-central1
